# Generated by Django 5.2.4 on 2025-08-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
