# Generated by Django 5.2.4 on 2025-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_db', '0002_rename_movie_id_movieinfo_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='release_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
