# Generated by Django 5.2.4 on 2025-08-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_db', '0003_movieinfo_release_year_alter_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='release_year',
            new_name='year',
        ),
    ]
